/// Static lists used in form dropdowns and chips
class AppLists {
  AppLists._();

  static const List<String> genders = [
    'Male',
    'Female',
    'Other',
  ];

  /// Common medical specializations (alphabetical).
  static const List<String> specializations = [
    'Algiatrist',
    'Allergy & Immunology',
    'Andrology',
    'Anesthesiology',
    'Ayurveda',
    'Ayurvedic and Unani Medicine',
    'Cardiology',
    'Cardiothoracic Surgery',
    'Chest Specialist',
    'Critical Care Medicine',
    'CTVS',
    'Dental Surgery',
    'Dentistry',
    'Dentistry (Oral and Maxillofacial Surgery)',
    'Dermatology',
    'Diabetology',
    'Emergency Medicine',
    'Endocrinology',
    'ENT',
    'ENT (Otolaryngology)',
    'Family Medicine',
    'Gastroenterology',
    'General Medicine',
    'General Physician',
    'General Surgery',
    'Geriatrics',
    'Gynecologic Oncology',
    'Gynecology',
    'Gynecology & Obstetrics',
    'Hematology',
    'Hepatology',
    'Homeopathy',
    'Infectious Disease',
    'Infertility & IVF Specialist (Gynecology)',
    'Internal Medicine',
    'Kidney Transplant',
    'Laparoscopic Urologic Surgery',
    'Laparoscopy',
    'Laser treatment',
    'Medical Oncology',
    'Neonatology',
    'Nephrology',
    'Neurology',
    'Neuropsychiatry',
    'Neurosurgery',
    'Neurosurgeon',
    'Nutrition & Dietetics',
    'Obstetrics',
    'Obstetrics and Gynecology (OB-GYN)',
    'Oncological Surgeon',
    'Oncology',
    'Ophthalmic Surgery',
    'Ophthalmology',
    'Optometrist',
    'Orthopedics',
    'Pain Management',
    'Pathology',
    'Pediatric Hemato-Oncologist',
    'Pediatric Surgery',
    'Pediatrics',
    'Physiotherapy',
    'Plastic Surgery',
    'PRP Therapy (Hair transplant)',
    'Psychiatry',
    'Pulmonology',
    'Radiation Oncology',
    'Radiology',
    'Reconstructive Surgery',
    'Rehabilitation Medicine',
    'Reproductive Endocrinology (IVF)',
    'Respiratory Medicine',
    'Rheumatology',
    'Skin & Beauty Specialist',
    'Sleep Medicine',
    'Sonology',
    'Sports Medicine',
    'Surgical Oncology',
    'Trauma Surgery',
    'Urology',
    'Vascular Surgery',
  ];

  static const List<String> languages = [
    'English',
    'Hindi',
    'Tamil',
    'Telugu',
    'Kannada',
    'Malayalam',
    'Marathi',
    'Bengali',
    'Gujarati',
    'Punjabi',
  ];
}
