/// Karnataka districts, taluk headquarters, and search aliases.
/// City pickers use this so every district and town is findable.
const karnatakaDistricts = [
  'Bagalkote',
  'Ballari',
  'Belagavi',
  'Bengaluru Rural',
  'Bengaluru Urban',
  'Bidar',
  'Chamarajanagara',
  'Chikkaballapura',
  'Chikkamagaluru',
  'Chitradurga',
  'Dakshina Kannada',
  'Davanagere',
  'Dharwad',
  'Gadag',
  'Hassan',
  'Haveri',
  'Kalaburagi',
  'Kodagu',
  'Kolar',
  'Koppal',
  'Mandya',
  'Mysuru',
  'Raichur',
  'Ramanagara',
  'Shivamogga',
  'Tumakuru',
  'Udupi',
  'Uttara Kannada',
  'Vijayapura',
  'Vijayanagara',
  'Yadgir',
];

/// Canonical city / taluk names (no duplicate colonial spellings).
const karnatakaCitiesAndTowns = [
  // Bengaluru Urban / Rural
  'Bengaluru',
  'Anekal',
  'Yelahanka',
  'Devanahalli',
  'Doddaballapura',
  'Hoskote',
  'Nelamangala',
  'Electronic City',
  'Whitefield',
  // Mysuru / Mandya / Kodagu / Chamarajanagara
  'Mysuru',
  'Nanjangud',
  'Hunsur',
  'Periyapatna',
  'K.R. Nagar',
  'H.D. Kote',
  'T. Narasipura',
  'Saragur',
  'Saligrama',
  'Mandya',
  'Maddur',
  'Malavalli',
  'Srirangapatna',
  'Pandavapura',
  'Nagamangala',
  'Krishnarajpet',
  'Madikeri',
  'Virajpet',
  'Somwarpet',
  'Kushalnagar',
  'Ponnampet',
  'Chamarajanagara',
  'Gundlupet',
  'Kollegal',
  'Yelandur',
  'Hanur',
  // Coastal
  'Mangaluru',
  'Udupi',
  'Manipal',
  'Puttur',
  'Bantwal',
  'Belthangady',
  'Sullia',
  'Moodbidri',
  'Ullal',
  'Mulki',
  'Kadaba',
  'Karkala',
  'Kundapura',
  'Brahmavar',
  'Byndoor',
  'Kaup',
  'Hebri',
  'Karwar',
  'Sirsi',
  'Kumta',
  'Bhatkal',
  'Honnavar',
  'Ankola',
  'Dandeli',
  'Haliyal',
  'Yellapur',
  'Siddapur',
  'Mundgod',
  'Joida',
  // Kalaburagi division
  'Kalaburagi',
  'Aland',
  'Afzalpur',
  'Chincholi',
  'Chittapur',
  'Jevargi',
  'Sedam',
  'Shahabad',
  'Wadi',
  'Kamalapur',
  'Yedrami',
  'Kalagi',
  'Bidar',
  'Basavakalyan',
  'Bhalki',
  'Humnabad',
  'Aurad',
  'Chitgoppa',
  'Kamalnagar',
  'Hulsoor',
  'Yadgir',
  'Shahapur',
  'Shorapur',
  'Gurmitkal',
  'Hunasagi',
  'Wadagera',
  'Raichur',
  'Sindhanur',
  'Manvi',
  'Lingasugur',
  'Devadurga',
  'Maski',
  'Sirwar',
  'Koppal',
  'Gangavathi',
  'Kushtagi',
  'Yelburga',
  'Kanakagiri',
  'Karatagi',
  'Kukanoor',
  'Ballari',
  'Siruguppa',
  'Sandur',
  'Kudligi',
  'Hosapete',
  'Hadagalli',
  'Hagaribommanahalli',
  'Kampli',
  'Harapanahalli',
  'Kotturu',
  'Kurugodu',
  'Hampi',
  'Vijayapura',
  'Indi',
  'Sindagi',
  'Basavana Bagewadi',
  'Muddebihal',
  'Talikoti',
  'Chadchan',
  'Tikota',
  'Nidagundi',
  'Bableshwar',
  'Bagalkote',
  'Jamkhandi',
  'Mudhol',
  'Badami',
  'Hungund',
  'Ilkal',
  'Bilagi',
  'Guledgudda',
  'Rabkavi Banhatti',
  'Terdal',
  // Belagavi / Dharwad / Haveri / Gadag
  'Belagavi',
  'Athani',
  'Chikkodi',
  'Gokak',
  'Nippani',
  'Bailhongal',
  'Hukkeri',
  'Khanapur',
  'Ramdurg',
  'Savadatti',
  'Raybag',
  'Mudalgi',
  'Kagwad',
  'Kittur',
  'Yaragatti',
  'Hubballi',
  'Dharwad',
  'Kalghatgi',
  'Kundgol',
  'Navalgund',
  'Alnavar',
  'Annigeri',
  'Gadag',
  'Mundargi',
  'Nargund',
  'Ron',
  'Shirahatti',
  'Gajendragad',
  'Lakshmeshwar',
  'Haveri',
  'Ranebennur',
  'Byadgi',
  'Hangal',
  'Hirekerur',
  'Savanur',
  'Shiggaon',
  'Rattihalli',
  // Central / Malnad
  'Shivamogga',
  'Bhadravati',
  'Sagara',
  'Thirthahalli',
  'Shikaripura',
  'Soraba',
  'Hosanagara',
  'Chikkamagaluru',
  'Kadur',
  'Tarikere',
  'Mudigere',
  'Koppa',
  'Sringeri',
  'Narasimharajapura',
  'Ajjampura',
  'Sakleshpur',
  'Hassan',
  'Arsikere',
  'Belur',
  'Holenarasipura',
  'Channarayapatna',
  'Arkalgud',
  'Alur',
  'Davanagere',
  'Harihara',
  'Channagiri',
  'Honnali',
  'Jagalur',
  'Nyamati',
  'Chitradurga',
  'Challakere',
  'Hiriyur',
  'Hosadurga',
  'Holalkere',
  'Molakalmuru',
  'Tumakuru',
  'Tiptur',
  'Sira',
  'Kunigal',
  'Gubbi',
  'Madhugiri',
  'Pavagada',
  'Koratagere',
  'Chiknayakanhalli',
  'Turuvekere',
  'Kolar',
  'Malur',
  'Bangarapet',
  'Kolar Gold Fields',
  'Mulbagal',
  'Srinivaspur',
  'Chikkaballapura',
  'Chintamani',
  'Sidlaghatta',
  'Gauribidanur',
  'Bagepalli',
  'Gudibande',
  'Chelur',
  'Ramanagara',
  'Channapatna',
  'Kanakapura',
  'Magadi',
  'Harohalli',
];

/// Old / alternate spellings used in GPS and search.
const karnatakaPlaceAliases = <String, List<String>>{
  'Bagalkote': ['Bagalkot'],
  'Ballari': ['Bellary'],
  'Belagavi': ['Belgaum'],
  'Bengaluru': ['Bangalore', 'Bengalooru'],
  'Bengaluru Rural': ['Bangalore Rural', 'Bengaluru Rural District'],
  'Bengaluru Urban': ['Bangalore', 'Bangalore Urban', 'Bengaluru Urban District'],
  'Chamarajanagara': ['Chamarajanagar'],
  'Chikkaballapura': ['Chikkaballapur'],
  'Chikkamagaluru': ['Chikmagalur', 'Chikmagaluru'],
  'Davanagere': ['Davangere'],
  'Hosapete': ['Hospet'],
  'Hubballi': ['Hubli', 'Hubli-Dharwad', 'Hubballi-Dharwad'],
  'Jevargi': ['Jewargi'],
  'Kalaburagi': ['Gulbarga'],
  'Mangaluru': ['Mangalore'],
  'Mysuru': ['Mysore'],
  'Shivamogga': ['Shimoga'],
  'Tumakuru': ['Tumkur'],
  'Vijayapura': ['Bijapur'],
  'Vijayanagara': ['Hosapete', 'Hospet', 'Hampi'],
  'Yadgir': ['Yadagiri'],
};

bool karnatakaPlaceMatchesQuery(String name, String query) {
  final q = query.trim().toLowerCase();
  if (q.isEmpty) return true;
  if (name.toLowerCase().contains(q)) return true;
  final aliases = karnatakaPlaceAliases[name];
  if (aliases == null) return false;
  for (final alias in aliases) {
    if (alias.toLowerCase().contains(q)) return true;
  }
  return false;
}

/// Towns that are not already listed as district names, sorted A–Z.
final List<String> karnatakaCanonicalTowns = _uniqueSorted(
  karnatakaCitiesAndTowns.where((town) {
    final key = town.trim().toLowerCase();
    return !karnatakaDistricts.any((d) => d.toLowerCase() == key);
  }).toList(),
);

/// Deduped search-ready Karnataka names: all 31 districts first, then towns.
final List<String> karnatakaSearchPlaces = [
  ...karnatakaDistricts,
  ...karnatakaCanonicalTowns,
];

List<String> _uniqueSorted(List<String> values) {
  final seen = <String>{};
  final result = <String>[];
  for (final value in values) {
    final key = value.trim().toLowerCase();
    if (key.isEmpty || seen.contains(key)) continue;
    seen.add(key);
    result.add(value.trim());
  }
  result.sort((a, b) => a.toLowerCase().compareTo(b.toLowerCase()));
  return result;
}
