const mongoose = require('mongoose');
const { BOOKING_STATUSES } = require('../ambulanceConstants');

const requirementSchema = new mongoose.Schema(
  {
    oxygen: { type: Boolean, default: false },
    ventilator: { type: Boolean, default: false },
    cardiacMonitor: { type: Boolean, default: false },
    icuSupport: { type: Boolean, default: false },
    stretcher: { type: Boolean, default: false },
    wheelchair: { type: Boolean, default: false },
    neonatal: { type: Boolean, default: false },
    medicalAttendant: { type: Boolean, default: false },
  },
  { _id: false },
);

const fareBreakdownSchema = new mongoose.Schema(
  {
    baseFare: { type: Number, default: 0 },
    distanceCharge: { type: Number, default: 0 },
    timeCharge: { type: Number, default: 0 },
    typeCharge: { type: Number, default: 0 },
    equipmentCharge: { type: Number, default: 0 },
    emergencySurcharge: { type: Number, default: 0 },
    nightCharge: { type: Number, default: 0 },
    waitingCharge: { type: Number, default: 0 },
    additionalCharge: { type: Number, default: 0 },
    total: { type: Number, default: 0 },
    estimated: { type: Boolean, default: true },
    currency: { type: String, default: 'INR' },
    distanceKm: Number,
    durationMinutes: Number,
  },
  { _id: false },
);

const ambulanceBookingSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    ambulanceId: { type: String, index: true },
    ambulanceServiceName: String,
    patientId: { type: String, index: true },
    patientName: { type: String, required: true },
    patientMobile: { type: String, required: true },
    patientEmail: String,
    patientAge: Number,
    patientGender: String,
    patientCondition: String,
    consciousState: {
      type: String,
      enum: ['conscious', 'unconscious', 'unknown'],
      default: 'unknown',
    },
    emergencyCategory: String,
    contactPerson: String,
    contactPhone: String,
    pickupAddress: { type: String, required: true },
    pickupCity: String,
    pickupPincode: String,
    pickupLatitude: Number,
    pickupLongitude: Number,
    dropAddress: String,
    dropCity: String,
    dropLatitude: Number,
    dropLongitude: Number,
    destinationType: {
      type: String,
      enum: ['hospital', 'home', 'clinic', 'other'],
      default: 'other',
    },
    destinationHospitalName: String,
    destinationHospitalId: String,
    notes: String,
    vehicleTypeRequested: String,
    requirements: { type: requirementSchema, default: () => ({}) },
    bookingKind: {
      type: String,
      enum: ['emergency', 'scheduled'],
      default: 'emergency',
      index: true,
    },
    scheduledAt: Date,
    isEmergency: { type: Boolean, default: true },
    status: {
      type: String,
      enum: BOOKING_STATUSES,
      default: 'requested',
      index: true,
    },
    rejectionReason: String,
    cancelReason: String,
    cancelledBy: String,
    estimatedArrivalMinutes: Number,
    assignedVehicleId: String,
    assignedDriverId: String,
    assignedDriverName: String,
    assignedVehicleRegistration: String,
    assignedVehicleType: String,
    currentDispatchId: String,
    dispatchRound: { type: Number, default: 0 },
    dispatchExpiresAt: Date,
    searchRadiusKm: Number,
    lastDispatchAt: Date,
    offeredAmbulanceIds: { type: [String], default: [] },
    liveLatitude: Number,
    liveLongitude: Number,
    liveAccuracy: Number,
    liveHeading: Number,
    liveSpeed: Number,
    liveLocationUpdatedAt: Date,
    pickupTime: Date,
    patientPickedUpAt: Date,
    destinationArrivalAt: Date,
    completedAt: Date,
    tripDistanceKm: Number,
    tripDurationMinutes: Number,
    tripNotes: String,
    fare: { type: fareBreakdownSchema, default: undefined },
    paymentStatus: {
      type: String,
      enum: ['unpaid', 'pending', 'paid', 'failed', 'refunded', 'cash'],
      default: 'unpaid',
    },
    paymentMethod: {
      type: String,
      enum: ['online', 'cash', 'none'],
      default: 'online',
    },
    paymentPolicy: String,
    razorpayOrderId: String,
    razorpayPaymentId: String,
    paymentExpiresAt: Date,
    refundAmount: Number,
    idempotencyKey: { type: String, index: true, sparse: true },
    locationUnavailable: { type: Boolean, default: false },
  },
  { timestamps: true },
);

ambulanceBookingSchema.index({ patientId: 1, createdAt: -1 });
ambulanceBookingSchema.index({ ambulanceId: 1, status: 1, createdAt: -1 });
ambulanceBookingSchema.index({ status: 1, bookingKind: 1, createdAt: -1 });
ambulanceBookingSchema.index({ assignedVehicleId: 1, status: 1 });
ambulanceBookingSchema.index(
  { assignedVehicleId: 1 },
  {
    unique: true,
    partialFilterExpression: {
      assignedVehicleId: { $type: 'string' },
      status: {
        $in: [
          'ambulance_assigned',
          'driver_accepted',
          'accepted',
          'dispatched',
          'driver_en_route',
          'en_route',
          'arrived_at_pickup',
          'arrived',
          'patient_picked_up',
          'en_route_to_destination',
          'arrived_at_destination',
        ],
      },
    },
  },
);

module.exports = mongoose.model('AmbulanceBooking', ambulanceBookingSchema);
