const mongoose = require('mongoose');

const vehicleSchema = new mongoose.Schema(
  {
    id: { type: String, required: true },
    registrationNumber: String,
    vehicleType: {
      type: String,
      // basic, bls, als, icu, cardiac, trauma, neonatal, pediatric,
      // isolation, bariatric, patient_transport, first_responder, air, mortuary, event
    },
    make: String,
    model: String,
    year: Number,
    color: String,
    capacity: Number,
    hasOxygen: { type: Boolean, default: false },
    hasVentilator: { type: Boolean, default: false },
    hasDefibrillator: { type: Boolean, default: false },
    hasStretcher: { type: Boolean, default: false },
    hasAed: { type: Boolean, default: false },
    hasCardiacMonitor: { type: Boolean, default: false },
    hasWheelchair: { type: Boolean, default: false },
    hasIcuCapability: { type: Boolean, default: false },
    hasNeonatalCapability: { type: Boolean, default: false },
    hasMedicalAttendant: { type: Boolean, default: false },
    equipment: { type: [String], default: [] },
    status: {
      type: String,
      enum: ['AVAILABLE', 'BUSY', 'OFFLINE', 'MAINTENANCE', 'EMERGENCY_ONLY'],
      default: 'OFFLINE',
    },
    assignedDriverId: String,
    currentBookingId: String,
    currentLatitude: Number,
    currentLongitude: Number,
    lastLocationAt: Date,
    lastLocationAccuracy: Number,
    lastLocationHeading: Number,
    lastLocationSpeed: Number,
    serviceRadiusKm: Number,
    baseFare: Number,
    perKm: Number,
    minFare: Number,
    rcBookUrl: String,
    insuranceUrl: String,
    fitnessCertificateUrl: String,
    pollutionCertificateUrl: String,
    photoFrontUrl: String,
    photoBackUrl: String,
    photoInteriorUrl: String,
  },
  { _id: false },
);

const driverSchema = new mongoose.Schema(
  {
    id: { type: String, required: true },
    fullName: String,
    mobileNumber: String,
    email: String,
    dateOfBirth: String,
    drivingLicenseNumber: String,
    drivingLicenseExpiry: String,
    emtCertificationNumber: String,
    emtCertificationExpiry: String,
    assignedVehicleId: String,
    governmentIdUrl: String,
    drivingLicenseUrl: String,
    emtCertificateUrl: String,
    photoUrl: String,
    backgroundCheckConsent: { type: Boolean, default: false },
    status: {
      type: String,
      enum: ['AVAILABLE', 'ON_TRIP', 'OFFLINE', 'ON_BREAK', 'SUSPENDED'],
      default: 'OFFLINE',
    },
    verificationStatus: {
      type: String,
      enum: ['pending', 'verified', 'rejected'],
      default: 'pending',
    },
    emergencyContactName: String,
    emergencyContactPhone: String,
    pinHash: String,
    isOnline: { type: Boolean, default: false },
    currentLatitude: Number,
    currentLongitude: Number,
    lastLocationAt: Date,
    lastOnlineAt: Date,
    currentBookingId: String,
  },
  { _id: false },
);

const ambulanceSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    serviceName: String,
    ownerName: String,
    email: { type: String, unique: true, sparse: true },
    mobileNumber: String,
    countryCode: { type: String, default: '91' },
    passwordHash: String,
    profilePicture: String,
    emergencyContact: String,
    licenseNumber: String,
    registrationNumber: String,
    panNumber: String,
    gstNumber: String,
    companyRegistrationNumber: String,
    vehicleCount: Number,
    vehicleTypes: [String],
    vehicles: { type: [vehicleSchema], default: [] },
    drivers: { type: [driverSchema], default: [] },
    address: String,
    city: String,
    state: String,
    pincode: String,
    latitude: Number,
    longitude: Number,
    serviceArea: String,
    serviceRadiusKm: { type: Number, default: 15 },
    supportedCities: { type: [String], default: [] },
    available24x7: { type: Boolean, default: false },
    emergencyAvailable: { type: Boolean, default: true },
    operatingHoursStart: { type: String, default: '00:00' },
    operatingHoursEnd: { type: String, default: '23:59' },
    cashPaymentEnabled: { type: Boolean, default: true },
    baseFare: { type: Number, default: 400 },
    perKm: { type: Number, default: 20 },
    minFare: { type: Number, default: 0 },
    fcmTokens: { type: [String], default: [] },
    isDisabled: { type: Boolean, default: false },
    isSuspended: { type: Boolean, default: false },
    ratingAverage: { type: Number, default: 0 },
    reviewCount: { type: Number, default: 0 },
    serviceLicenseUrl: String,
    companyRegistrationUrl: String,
    gstCertificateUrl: String,
    fleetInsuranceUrl: String,
    bankAccountHolderName: String,
    bankAccountNumber: String,
    ifscCode: String,
    bankName: String,
    cancelledChequeUrl: String,
    verificationStatus: { type: String, default: 'pending', index: true },
    rejectionReason: String,
    isApproved: { type: Boolean, default: false },
    approvalNotes: String,
  },
  { timestamps: true },
);

ambulanceSchema.index({ verificationStatus: 1, isDisabled: 1, isSuspended: 1 });
ambulanceSchema.index({ city: 1, verificationStatus: 1 });

module.exports = mongoose.model('Ambulance', ambulanceSchema);
