const mongoose = require('mongoose');

const vehicleSchema = new mongoose.Schema(
  {
    id: { type: String, required: true },
    registrationNumber: String,
    vehicleType: String,
    make: String,
    model: String,
    year: Number,
    color: String,
    capacity: Number,
    hasOxygen: { type: Boolean, default: false },
    hasVentilator: { type: Boolean, default: false },
    hasDefibrillator: { type: Boolean, default: false },
    hasStretcher: { type: Boolean, default: false },
    hasAed: { type: Boolean, default: false },
    rcBookUrl: String,
    insuranceUrl: String,
    fitnessCertificateUrl: String,
    pollutionCertificateUrl: String,
    photoFrontUrl: String,
    photoBackUrl: String,
    photoInteriorUrl: String,
  },
  { _id: false },
);

const driverSchema = new mongoose.Schema(
  {
    id: { type: String, required: true },
    fullName: String,
    mobileNumber: String,
    email: String,
    dateOfBirth: String,
    drivingLicenseNumber: String,
    drivingLicenseExpiry: String,
    emtCertificationNumber: String,
    emtCertificationExpiry: String,
    assignedVehicleId: String,
    governmentIdUrl: String,
    drivingLicenseUrl: String,
    emtCertificateUrl: String,
    photoUrl: String,
    backgroundCheckConsent: { type: Boolean, default: false },
  },
  { _id: false },
);

const ambulanceSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    serviceName: String,
    ownerName: String,
    email: { type: String, unique: true, sparse: true },
    mobileNumber: String,
    passwordHash: String,
    profilePicture: String,
    emergencyContact: String,
    licenseNumber: String,
    registrationNumber: String,
    panNumber: String,
    gstNumber: String,
    companyRegistrationNumber: String,
    vehicleCount: Number,
    vehicleTypes: [String],
    vehicles: { type: [vehicleSchema], default: [] },
    drivers: { type: [driverSchema], default: [] },
    address: String,
    city: String,
    state: String,
    pincode: String,
    latitude: Number,
    longitude: Number,
    serviceArea: String,
    available24x7: { type: Boolean, default: false },
    serviceLicenseUrl: String,
    companyRegistrationUrl: String,
    gstCertificateUrl: String,
    fleetInsuranceUrl: String,
    bankAccountHolderName: String,
    bankAccountNumber: String,
    ifscCode: String,
    bankName: String,
    cancelledChequeUrl: String,
    verificationStatus: { type: String, default: 'pending', index: true },
    rejectionReason: String,
    isApproved: { type: Boolean, default: false },
    approvalNotes: String,
  },
  { timestamps: true },
);

module.exports = mongoose.model('Ambulance', ambulanceSchema);
