const mongoose = require('mongoose');

const bloodOrderSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    bloodBankId: { type: String, required: true, index: true },
    patientId: String,
    patientName: String,
    patientMobile: String,
    patientEmail: String,
    patientAge: Number,
    patientGender: String,
    hospitalName: String,
    hospitalAddress: String,
    doctorName: String,
    doctorContact: String,
    requiredDate: Date,
    requiredTime: String,
    requestType: {
      type: String,
      enum: ['normal', 'emergency'],
      default: 'normal',
      index: true,
    },
    bloodGroup: { type: String, required: true },
    componentType: { type: String, required: true },
    units: { type: Number, required: true, min: 1 },
    prescriptionUrl: String,
    reservationId: String,
    reservationExpiresAt: Date,
    deliveryMethod: {
      type: String,
      enum: ['home_delivery', 'self_pickup', 'hospital_delivery'],
      default: 'self_pickup',
    },
    deliveryAddress: String,
    deliveryDate: Date,
    deliveryTimeSlot: String,
    couponCode: String,
    discountAmount: { type: Number, default: 0 },
    baseAmount: { type: Number, default: 0 },
    totalAmount: { type: Number, default: 0 },
    paymentMethod: { type: String, enum: ['online', 'cash'], default: 'online' },
    paymentStatus: { type: String, default: 'pending' },
    razorpayOrderId: String,
    razorpayPaymentId: String,
    paymentExpiresAt: Date,
    status: {
      type: String,
      enum: [
        'pending',
        'blood_bank_notified',
        'under_review',
        'accepted',
        'blood_reserved',
        'payment_pickup',
        'ready_for_collection',
        'blood_ready',
        'out_for_delivery',
        'collected',
        'delivered',
        'completed',
        'rejected',
        'cancelled',
        'expired',
      ],
      default: 'pending',
      index: true,
    },
    rejectionReason: String,
    rejectionReasonCode: {
      type: String,
      enum: [
        'blood_unavailable',
        'insufficient_quantity',
        'component_unavailable',
        'information_incomplete',
        'documentation_issue',
        'other',
      ],
    },
    isEmergency: { type: Boolean, default: false },
    estimatedDeliveryTime: Date,
    invoiceUrl: String,
    notes: String,
    deliveryContact: String,
    assignedStaffId: String,
    deliveryStatus: {
      type: String,
      enum: ['not_applicable', 'pending', 'assigned', 'in_transit', 'arrived', 'delivered'],
      default: 'not_applicable',
    },
    chatEnabled: { type: Boolean, default: false },
  },
  { timestamps: true },
);

module.exports = mongoose.model('BloodOrder', bloodOrderSchema);
