const mongoose = require('mongoose');

const doctorSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    firstName: String,
    lastName: String,
    email: { type: String, unique: true, sparse: true },
    emailVerified: { type: Boolean, default: false },
    emailVerifiedAt: Date,
    mobileNumber: String,
    countryCode: { type: String, default: '91' },
    phoneVerified: { type: Boolean, default: false },
    phoneVerifiedAt: Date,
    passwordHash: String,
    profilePicture: String,
    gender: String,
    dateOfBirth: String,
    medicalRegistrationNumber: String,
    medicalCouncilName: String,
    specializations: { type: [String], default: [] },
    qualification: String,
    yearsOfExperience: Number,
    clinicName: String,
    consultationFee: Number,
    onlineConsultFee: Number,
    homeVisitFee: Number,
    visitSiteFee: Number,
    onlineConsultOfferFee: Number,
    homeVisitOfferFee: Number,
    visitSiteOfferFee: Number,
    offersOnlineConsult: { type: Boolean, default: false },
    offersBookHome: { type: Boolean, default: false },
    offersVisitSite: { type: Boolean, default: false },
    languagesSpoken: { type: [String], default: [] },
    bio: String,
    address: String,
    city: String,
    state: String,
    pincode: String,
    latitude: Number,
    longitude: Number,
    medicalLicenseUrl: String,
    governmentIdUrl: String,
    degreeCertificateUrl: String,
    clinicProofUrl: String,
    bankAccountNumber: String,
    ifscCode: String,
    cancelledChequeUrl: String,
    payoutMethod: {
      type: String,
      enum: ['bank', 'upi'],
      default: 'bank',
    },
    upiId: String,
    aadhaarLast4: String,
    aadhaarCardUrl: String,
    hospitalPhoto1Url: String,
    hospitalPhoto2Url: String,
    hospitalPhoto3Url: String,
    hospitalPhoto4Url: String,
    hospitalPhoto5Url: String,
    aadhaarVerified: { type: Boolean, default: false },
    aadhaarVerifiedAt: Date,
    verificationStatus: { type: String, default: 'pending', index: true },
    rejectionReason: String,
    isApproved: { type: Boolean, default: false },
    approvalNotes: String,
    lastActiveAt: { type: Date, default: null, index: true },
    averageRating: { type: Number, default: null },
    ratingCount: { type: Number, default: 0 },
    fcmTokens: { type: [String], default: [] },
  },
  { timestamps: true },
);

module.exports = mongoose.model('Doctor', doctorSchema);
