const mongoose = require('mongoose');

const nurseSchema = new mongoose.Schema(
  {
    id: { type: String, required: true, unique: true, index: true },
    firstName: String,
    lastName: String,
    email: { type: String, unique: true, sparse: true },
    mobileNumber: String,
    countryCode: { type: String, default: '91' },
    passwordHash: String,
    profilePicture: String,
    gender: String,
    dateOfBirth: Date,
    languagesSpoken: { type: [String], default: [] },
    emergencyContactName: String,
    emergencyContactNumber: String,
    qualification: String,
    registrationNumber: String,
    nursingCouncil: String,
    nuid: String,
    yearsOfExperience: Number,
    specialization: String,
    nursingSkills: { type: [String], default: [] },
    address: String,
    city: String,
    state: String,
    pincode: String,
    latitude: Number,
    longitude: Number,
    serviceRadiusKm: Number,
    availableForHomeVisit: { type: Boolean, default: true },
    homeVisitFee: Number,
    homeVisitOfferFee: Number,
    shiftAvailability: String,
    bankAccountHolderName: String,
    bankAccountNumber: String,
    ifscCode: String,
    bankName: String,
    verificationStatus: { type: String, default: 'pending', index: true },
    rejectionReason: String,
    isApproved: { type: Boolean, default: false },
    approvalNotes: String,
    averageRating: { type: Number, default: null },
    ratingCount: { type: Number, default: 0 },
    lastActiveAt: { type: Date, default: null, index: true },
    fcmTokens: { type: [String], default: [] },
  },
  { timestamps: true },
);

module.exports = mongoose.model('Nurse', nurseSchema);
