function normalizeVerificationStatus(status) {
  if (status === 'verifier_approved') return 'under_review';
  return status;
}

function toLab(doc) {
  if (!doc) return null;
  const d = doc.toObject ? doc.toObject() : doc;
  return {
    id: d.id,
    labName: d.labName,
    ownerName: d.ownerName,
    email: d.email,
    mobileNumber: d.mobileNumber,
    countryCode: d.countryCode || '91',
    profilePicture: d.profilePicture,
    address: d.address,
    city: d.city,
    state: d.state,
    pincode: d.pincode,
    latitude: d.latitude,
    longitude: d.longitude,
    gstNumber: d.gstNumber,
    licenseNumber: d.licenseNumber,
    accreditation: d.accreditation,
    operatingHours: d.operatingHours,
    homeCollectionAvailable: Boolean(d.homeCollectionAvailable),
    available24x7: Boolean(d.available24x7),
    coverImage: d.coverImage,
    labType: d.labType,
    yearEstablished: d.yearEstablished,
    registrationNumber: d.registrationNumber,
    nablAccreditationNumber: d.nablAccreditationNumber,
    otherCertifications: d.otherCertifications,
    buildingName: d.buildingName,
    street: d.street,
    area: d.area,
    landmark: d.landmark,
    openingTime: d.openingTime,
    closingTime: d.closingTime,
    workingDays: d.workingDays || [],
    emergencyServiceAvailable: Boolean(d.emergencyServiceAvailable),
    facilities: d.facilities || [],
    supportedCategories: d.supportedCategories || [],
    offeredTests: d.offeredTests || [],
    healthPackages: d.healthPackages || [],
    offeredScans: d.offeredScans || [],
    staffMembers: d.staffMembers || [],
    bankDetails: d.bankDetails || null,
    serviceCities: d.serviceCities || [],
    serviceAreas: d.serviceAreas || [],
    homeCollectionRadiusKm: d.homeCollectionRadiusKm,
    branches: d.branches || [],
    serviceablePincodes: d.serviceablePincodes || [],
    homeVisitSlots: d.homeVisitSlots || [],
    labImages: d.labImages || [],
    documents: d.documents || [],
    averageRating: d.averageRating ?? 4.5,
    reviewCount: d.reviewCount ?? 0,
    verificationStatus: normalizeVerificationStatus(d.verificationStatus),
    rejectionReason: d.rejectionReason,
    documentRequestNote: d.documentRequestNote,
    isApproved: Boolean(d.isApproved),
    approvalNotes: d.approvalNotes,
    createdAt: d.createdAt,
    updatedAt: d.updatedAt,
  };
}

module.exports = { toLab };
